logging:
  level:
    com:
      mallplus:
        mall:
          cms:
            mapper: debug
          mapper: debug
          oms:
            mapper: debug
          pms:
            mapper: debug
          sms:
            mapper: debug
          sys:
            mapper: debug
          ums:
            mapper: debug
      zscat:
        mallplus: debug
    root: info
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      column-underline: true
      db-type: mysql
      field-strategy: not_empty
      id-type: id_worker
      logic-delete-value: 0
      logic-not-delete-value: 1
    refresh: true
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.zscat.mallplus.*.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      maxActive: 10
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      remove-abandoned-timeout: 180
      removeAbandoned: true
      stat-view-servlet:
        enabled: true
        login-password: druid
        login-username: druid
        reset-enable: true
        url-pattern: /druid/*
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.1.55:3306/mallplus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
  redis:
    database: 2
    host: localhost
    password: ''
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 0
